### ISSUE TITLE
how to build and flash the sample code under external/zephyr

### ISSUE THREAD

**Issue by aaltonenzhang** [CurieBSP/main#1]
I have tried like:
1.export ZEPHYR_GCC_VARIANT=zephyr
  export ZEPHYR_SDK_INSTALL_DIR=~/zephyr-sdk
2.source ./zephyr-env.sh
3.cd ~/Curie_BSP/wearable_device_sw/external/zephyr/samples/nanokernel/apps/hello_world
4.make pristine
5.make BOARD=arduino_101
6.make BOARD=arduino_101 flash
The log said I've flashed the image. But nothing appears in my uart port.
Could U tell me where is wrong in my above steps? Thx!

**Comment by daltonal** [comment]
Hi,
If your goal is to flash the full curie BSP on your arduino_101 board, then you should follow instructions at: 
https://github.com/CurieBSP/main/releases.
If you want to only build zephyr os on your arduino_101 board, then I think you have the correct steps, however the zephyr version in this repo is pretty custom compared to the mainline zephyr.
In all cases,
https://wiki.zephyrproject.org/view/Arduino_101 has instructions on how to get Zephyr working on the arduino_101 board and the info on getting the serial port output are the same for CurieBSP.

**Comment by aaltonenzhang** [comment]
Thank you! Another question: if I replace the custom zephyr path with the standard zephyr in curie bsp, will the whole curie bsp project work well? For example, will the 3 project samples works well?

**Comment by daltonal** [comment]
No, it's not likely to work, CurieBSP needs some hooks in zephyr in order to work correctly.
What are you trying to achieve ? 
Next soon to come release will have zephyr rebased to 1.4 if this is what you are looking for.

**Comment by aaltonenzhang** [comment]
Actually, I need one uart to do something, and other port to print log. I found there is an i2c sample in zephyr. So before I tried it, I want to try the easier hello world sample first. But I found that the standard zephyr hello world works, and the custom zephyr doesn't. I have just tried once again and there's no uart out log. Should I import the standard zephyr to do this in specially?

**Comment by daltonal** [comment]
Again, what do you need exactly, is there a specific reason why are you looking at this project and not the standard zephyr then ?
