### ISSUE TITLE
gdb error with "make debug_console_qrk "

### ISSUE THREAD

**Issue by datangjack** [CurieBSP/main#2]
hi

I have burned Curie_ble  into arduino_101 board and encountered problem with gdb debug:
"During startup program terminated with signal SIGKILL, killed."

Could I make debug with Jlink emulator to debug program?

**Comment by sdesfar** [comment]
Hello,

Which command are you using to debug the board ? Which processor are you trying to connect to ?

JLINK debugger is not supported, you need to use a Flyswatter2.

Simon.

**Comment by datangjack** [comment]
1, debug command is " make debug_console_qrk " for curie_ble project. 
2, My board is Arduino_101(curie_101);
3. I modified the OPTION_JTAG_INTERFACE_CFG_FILE ?= "interface/ftdi/jlink.cfg"wearable_device_sw/projects/options.mk 
and added the jlink.cfg to the path.

BR
thanks

**Comment by sdesfar** [comment]
Can you share your hardware setup please ? JLINK jtag probe is not officially supported, but I can give a try :)

**Comment by aaltonenzhang** [comment]
Hi, sdesfar. Did you try what datangjack asked? I encountered the same problem.
