### ISSUE TITLE
Could I disable arc code in the project?

### ISSUE THREAD

**Issue by checkoutgithub** [CurieBSP/main#3]
How to only boot up quark code? If I directly delete arc path from any projects, how to modify make files?

**Comment by RCintel** [comment]
What is your purpose?

**Comment by checkoutgithub** [comment]
The purpose is to reduce the complexity of our project. We want to disable arc and malloc all flash size to quark. Sensor related issues (or other arc issues) are not needed now.

**Comment by dirac3000** [comment]
It is possible indeed to only boot Quark, but this is not officially supported on Quark SE. 
To prevent booting ARC, you will need to modify the soc_setup and bsp_init functions for Quark. Also, you will need to change partitions and flashing procedures.
Note that you will not be able to use all peripherals, e.g.: ADC, the BMI160, are connected and accessible only from ARC.
